Create mapa,html
Nircek/pikna-mapa pull request #12
Opened 2019-10-14 08:44 UTC by Monika452

2019-10-14 10:13 UTC, Nircek requested changes

2019-10-14 10:13 UTC, Nircek commented on index.html
> +  <frame name="gora" src="tytul.html">
U mnie górny frame zajmuje 100% wysokości i nie widać dolnego...

2019-10-14 10:13 UTC, Nircek commented on mapa.html
> +</head>
Nie wiem czy to wszystko jest potrzebne, jeżeli to jest tylko frame... Jakieś źródło?

2019-10-14 10:13 UTC, Nircek commented on mapa.html
> +    <div id="mapa"></div>
Mogłaś napisać tutaj chociaż jakieś "mapa", bo nie da się przetestować czy działa.

2019-10-14 10:13 UTC, Nircek commented on tytul.html
> +  </div>
Brzydkie to jest strasznie, mogłaś chociaż dać logo koło tytułu, a nie nad.

2019-10-14 10:22 UTC, Monika452 commented on index.html
> +  <frame name="gora" src="tytul.html">
ogarnięte

2019-10-14 10:25 UTC, Nircek commented on index.html
> +  <frame name="gora" src="tytul.html">
@Monika452 cały czas nie działa

2019-10-15 17:46 UTC, Nircek commented on index.html
> +  <frame name="gora" src="tytul.html">
ogarnięte w 0c70ce0

2019-10-15 17:49 UTC, Nircek approved these changes
Strasznie brzydkie to, ale jak chcesz to merguj @Monika452... Mam nadzieję, że potem ktoś to poprawi.

2019-10-16 17:14 UTC, Nircek commented
Merguję, bo bym coś już zrobił.

2019-10-16 17:15 UTC, merged